BEGIN;

DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS POSTS CASCADE;
DROP TABLE IF EXISTS COMMENTS CASCADE;

CREATE TABLE IF NOT EXISTS USERS(
    USER_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(28) UNIQUE NOT NULL,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    PASSWORD TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTS(
    POST_ID SERIAL PRIMARY KEY,
    "OWNER" INTEGER REFERENCES USERS(USER_ID) NOT NULL,
    TITLE TEXT NOT NULL,
    CONTENT TEXT,
    VOTES INTEGER DEFAULT 0
);

CREATE TABLE IF EXISTS COMMENTS(
    COMMENT_ID SERIAL PRIMARY KEY,
    "OWNER" INTEGER REFERENCES USERS(USER_ID) NOT NULL,
    POST INTEGER REFERENCES POSTS(POST_ID) NOT NULL
);


COMMIT;